# Generated by Django 4.0.6 on 2022-08-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_bookmark_cat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='cat_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='user_id',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
