# Generated by Django 4.0.6 on 2022-09-20 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat_inf', '0002_alter_cat_alert_alter_cat_neutral_alter_cat_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_tag', models.IntegerField()),
                ('cat_id', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=13, max_digits=17)),
                ('longitude', models.DecimalField(decimal_places=13, max_digits=17)),
                ('complaint_kind', models.TextField()),
                ('character', models.CharField(max_length=100)),
                ('author', models.EmailField(max_length=254, null=True)),
            ],
        ),
    ]
