# Generated by Django 4.0.5 on 2022-09-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat_inf', '0013_rename_complaint_kind_injury_injury_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='injury_count',
            field=models.IntegerField(default=0),
        ),
    ]
