# Generated by Django 4.0.6 on 2022-08-12 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat_inf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='cat_photo')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cat',
            name='alert',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cat',
            name='neutral',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cat',
            name='sex',
            field=models.IntegerField(),
        ),
    ]
