# Generated by Django 4.1 on 2022-08-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat_inf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='alert',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cat',
            name='neutral',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cat',
            name='sex',
            field=models.CharField(max_length=100),
        ),
    ]
