# Generated by Django 4.0.6 on 2022-08-13 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cat_inf', '0002_image_alter_cat_alert_alter_cat_neutral_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
