# Generated by Django 4.0.6 on 2022-09-20 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat_inf', '0003_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='author',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='cat_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='character',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='latitude',
            field=models.DecimalField(decimal_places=13, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='longitude',
            field=models.DecimalField(decimal_places=13, max_digits=17, null=True),
        ),
    ]
