# Generated by Django 4.0.6 on 2022-08-15 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat_inf', '0003_cat_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
