# Generated by Django 4.0.6 on 2022-09-20 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat_inf', '0005_complaint_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='character',
            field=models.TextField(null=True),
        ),
    ]
