# Generated by Django 4.0.6 on 2022-09-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat_inf', '0006_alter_complaint_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='complain_count',
            field=models.IntegerField(default=0),
        ),
    ]
