# Generated by Django 4.0.6 on 2022-09-21 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat_inf', '0007_cat_complain_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='complain_count',
            new_name='complaint_count',
        ),
    ]
