# Generated by Django 4.0.6 on 2022-09-21 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat_inf', '0009_feed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='user_id',
            new_name='author',
        ),
    ]
