# Generated by Django 4.0.5 on 2022-09-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat_inf', '0011_snack'),
    ]

    operations = [
        migrations.CreateModel(
            name='injury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_id', models.IntegerField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('complaint_kind', models.TextField()),
                ('character', models.TextField(null=True)),
                ('author', models.EmailField(max_length=254)),
            ],
        ),
    ]
