# Generated by Django 4.0.6 on 2022-09-25 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat_inf', '0014_cat_injury_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='character',
            field=models.TextField(null=True),
        ),
    ]
